apps:
  - id: "demo-app-1"
    name: "示例应用 1"
    description: "这是一个示例应用，用于演示功能。支持基本的用户界面和交互功能。"
    version: "1.0.0"
    file_path: "data/apps/demo-app-1.apk"
    detail_file_path: "data/apps/details/demo-app-1.md"
    screenshots:
      - "demo-app-1/screen1.png"
      - "demo-app-1/screen2.png"
      - "demo-app-1/screen3.png"
    category: "工具类"
    platform: "android"
    icon: "android"
    tags:
      - "工具"
      - "示例"
      - "Android"

  - id: "p2p-chat-app"
    name: "端对端加密加密聊天app"
    description: "基于Flutter的端对端加密群组聊天应用，支持多人群组聊天，采用去中心化架构，通过二维码进行群组邀请，确保消息传输的安全性。"
    version: "1.0.0"
    file_path: "data/apps/app-debug.apk"
    detail_file_path: "data/apps/details/p2p-chat-app.md"
    category: "工具类"
    platform: "android"
    icon: "android"
    tags:
      - "工具"
      - "示例"
      - "Android"
  
  - id: "demo-app-2"
    name: "示例应用 2"
    description: "另一个示例应用，展示不同功能。包含高级特性和自定义设置。"
    version: "2.1.0"
    file_path: "data/apps/demo-app-2.apk"
    detail_file_path: ""
    screenshots: []
    category: "娱乐类"
    platform: "android"
    icon: "games"
    tags:
      - "娱乐"
      - "游戏"
      - "Android"
  
  - id: "test-ios-app"
    name: "iOS测试应用"
    description: "iOS平台的测试应用，支持最新的iOS特性。"
    version: "1.5.2"
    file_path: "data/apps/test-ios-app.ipa"
    detail_file_path: ""
    screenshots:
      - "test-ios-app/ios-screen1.png"
      - "test-ios-app/ios-screen2.png"
    category: "工具类"
    platform: "ios"
    icon: "phone_iphone"
    tags:
      - "iOS"
      - "工具"
      - "测试"
  
  - id: "windows-tool"
    name: "Windows工具"
    description: "Windows桌面应用程序，提供系统优化功能。"
    version: "3.0.1"
    file_path: "data/apps/windows-tool.exe"
    detail_file_path: ""
    screenshots:
      - "windows-tool/win-screen1.png"
    category: "系统工具"
    platform: "windows"
    icon: "desktop_windows"
    tags:
      - "Windows"
      - "系统工具"
      - "优化"
  
  - id: "mac-app"
    name: "macOS应用"
    description: "macOS平台的应用，提供专业的图像处理功能。"
    version: "2.3.0"
    file_path: "data/apps/mac-app.dmg"
    detail_file_path: ""
    screenshots:
      - "mac-app/mac-screen1.png"
      - "mac-app/mac-screen2.png"
      - "mac-app/mac-screen3.png"
    category: "创意工具"
    platform: "mac"
    icon: "laptop_mac"
    tags:
      - "macOS"
      - "创意"
      - "图像处理"
  
  - id: "linux-utility"
    name: "Linux工具"
    description: "Linux命令行工具，提供系统监控和管理功能。"
    version: "1.8.5"
    file_path: "data/apps/linux-utility.tar.gz"
    detail_file_path: ""
    screenshots: []
    category: "系统工具"
    platform: "linux"
    icon: "terminal"
    tags:
      - "Linux"
      - "命令行"
      - "系统监控" 